### ISSUE TITLE
no popup firefox 45.02

### ISSUE THREAD

**Issue by heforfree** [cyril-we/ForgetThatPage#1]
hello thank you
chrome.history is undefined popup.js:21:0
chrome.history is undefined background.js:23:0

**Comment by cyril-we** [comment]
Thanks for bug notifications. 
Try to correct the popup with v1.3.0.1 available soon on Firefox addons and now on https://github.com/cyril-we/ForgetThatPage/releases/

**Comment by heforfree** [comment]
your welcome and thank you for update
i can see popup now
but still see this in log
chrome.history is undefined popup.js:21:0
and according to screenshot icon should be green which is for me gray
and i don't see text in popup that i see in screenshot

**Comment by cyril-we** [comment]
My extension uses chrome API, which is only supported since Firefox 49.
I changed the compatibility.
Which Firefox version are you currently using ?

**Comment by heforfree** [comment]
thank you firefox 45
i  now read  end of you older comment

**Comment by cyril-we** [comment]
Do you have the same problem using Firefox 49+ ?

**Comment by heforfree** [comment]
as i tested now it work on Nightly 52.0a1
i don't have other 46,47,48 or 49 version something was changed on them and are slow on my pc
but 52 is fine
