### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by Gittyperson** [cyril-we/ForgetThatPage#2]
Many thanks for your nice extension, looks very helpful.

It'd be great if you could also make it Pale Moon compatible. I think Forget that page for Firefox uses the WebExtensions system? In case you manage take a look, I'll just let you know that PM supports the classic XUL extensions. More extension-related technical info [here](https://www.palemoon.org/roadmap.shtml).

**Comment by cyril-we** [comment]
First, thanks for your interest on my extension.
I will have a look at Pale Moon and try make it compatible if possible.
